name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 */3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 20fd435a-3e08-47dd-995b-83f8bffd70cd
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
